# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/verilog/decoder38/decoder38.cache/wt [current_project]
set_property parent.project_path D:/verilog/decoder38/decoder38.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/verilog/decoder38/decoder38.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/verilog/decoder38/decoder38.srcs/sources_1/new/decoder38.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/verilog/decoder38/decoder38.srcs/constrs_1/new/mycons.xdc
set_property used_in_implementation false [get_files D:/verilog/decoder38/decoder38.srcs/constrs_1/new/mycons.xdc]


synth_design -top decoder38 -part xc7a200tfbg676-2


write_checkpoint -force -noxdef decoder38.dcp

catch { report_utilization -file decoder38_utilization_synth.rpt -pb decoder38_utilization_synth.pb }
