set_property PACKAGE_PIN AC22 [get_ports {myin[0]}]
set_property PACKAGE_PIN AD24 [get_ports {myin[1]}]
set_property PACKAGE_PIN AC21 [get_ports {myin[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {myin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myin[2]}]

set_property PACKAGE_PIN H7 [get_ports {myout[0]}]
set_property PACKAGE_PIN D5 [get_ports {myout[1]}]
set_property PACKAGE_PIN A3 [get_ports {myout[2]}]
set_property PACKAGE_PIN A5 [get_ports {myout[3]}]
set_property PACKAGE_PIN A4 [get_ports {myout[4]}]
set_property PACKAGE_PIN F7 [get_ports {myout[5]}]
set_property PACKAGE_PIN G8 [get_ports {myout[6]}]
set_property PACKAGE_PIN H8 [get_ports {myout[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {myout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {myout[7]}]